" Load pathogen
source ~/dotfiles/vimfiles/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}')
autocmd VimEnter * Helptags "loads pathogen help tags

" Reset options
set sessionoptions-=options

" General options
set encoding=utf-8
syntax enable
filetype plugin indent on
autocmd BufNewFile * startinsert
"starts in insert mode if file is new
set keywordprg=":help"
"<K> shows help for word under cursor
set mouse=""
"disable mouse support
set backspace=indent,eol,start
"backspace through everything in insert mode
set scrolloff=5
"leave some space between the cursor and edge of window

" Set color options
colorscheme slate-transparent
set termguicolors
"This is only necessary if you use "set termguicolors".
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
"fixes glitch? in colors when using vim with tmux
set t_Co=256

" Set visible elements
set title
set number
set ruler
set foldcolumn=4
set laststatus=2
"always show status line

" Wrap options
set nowrap "don't wrap by default
set linebreak "breaks at word rather than character
set breakindent
set showbreak=⤷

" Search options
set ignorecase
set smartcase "don't ignore case if uppercase letter(s) typed
set incsearch "highlight search as it's typed
set hlsearch

" Tab options
set noexpandtab
set tabstop=4
set softtabstop=-1
"use shiftwidth value
set shiftwidth=4
set autoindent
set smartindent
set nocindent
set indentexpr=""

" Split to right and bottom
set splitright
set splitbelow

" Timeout on keycodes
set ttimeout
set ttimeoutlen=50

" Show non-character items
set listchars=tab:\⋮\ ,eol:⏎,trail:␠,extends:▶,precedes:◀,nbsp:⎵
set list

" Set fold options
set foldmethod=syntax

" Chars for fold, vsplit, and eob
set fillchars=vert:\|,fold:\ ,foldopen:-,foldclose:+,foldsep:\|,eob:~

" Wildmenu options
set wildmenu "for command completion
set wildmode=longest:full,full


" Source other config files
source ~/dotfiles/vim/remaps.vim
