" Vimrc configuration file
" ---Hayden Atchley---


" Load pathogen
source ~/dotfiles/vimfiles/bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}')
autocmd VimEnter * Helptags "loads pathogen help tags


" Reset options
set sessionoptions-=options


" General options
set encoding=utf-8
syntax enable
filetype plugin indent on
"start in insert mode if file is new
autocmd BufNewFile * startinsert
"<K> to show help for word under cursor
set keywordprg=":help"
"disable mouse support
set mouse=""
"backspace through everything in insert mode
set backspace=indent,eol,start
"leave some space between the cursor and edge of window
set scrolloff=5


" Set color options
colorscheme slate-transparent
set termguicolors
"This is only necessary if you use "set termguicolors".
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
"fix glitch? in colors when using vim with tmux
set t_Co=256


" Set visible elements
set title
set number
set ruler
set foldcolumn=4
"always show status line
set laststatus=2

" Set relative line numbers except when in insert mode or not focused
augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
	autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END


" Wrap options
"don't wrap by default
set nowrap
"break at word rather than character
set linebreak
"indent broken (wrapped) lines
set breakindent
set showbreak=⤷


" Search options
set ignorecase
"don't ignore case if uppercase letter(s) typed
set smartcase
"highlight search as it's typed
set incsearch
set hlsearch


" Tab options
set noexpandtab
set tabstop=4
"use shiftwidth value
set softtabstop=-1
set shiftwidth=4
set autoindent
set smartindent
set nocindent
set indentexpr=""

" Text width
set textwidth=80

" Split to right and bottom
set splitright
set splitbelow


" Timeout on keycodes
set ttimeout
set ttimeoutlen=50


" Show non-character items
set listchars=tab:\⋮\ ,eol:⏎,trail:␠,extends:▶,precedes:◀,nbsp:⎵
set list


" Set fold options
set foldmethod=syntax


" Chars for fold, vsplit, and eob
set fillchars=vert:\|,fold:\ 


" Wildmenu options
"for command completion
set wildmenu
set wildmode=longest:full,full


" Source other config files
source ~/dotfiles/vim/remaps.vim
